import { Application } from "@/types";

export type MockPipelineStage = "APPLIED" | "SCREEN" | "INTERVIEW" | "OFFER" | "HIRED" | "REJECTED";
export type MockApplication = Application & { pipeline_stage: MockPipelineStage };

const now = Date.now();

const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export const mockAdminApplications: MockApplication[] = [
  {
    id: "app-001",
    user_id: "user-001",
    created_at: daysAgo(2),
    status: "reviewed",
    pipeline_stage: "SCREEN",
    type: "talent_pool_registration",
    name: "Yasmine El Idrissi",
    email: "yasmine.elidrissi@example.com",
    phone: "+212612345678",
    sap_track: "FI",
    german_level: "B2",
    experience_years: 4,
    admin_rating: 4,
    admin_notes: "Strong communication and good finance project portfolio.",
    ai_analysis_summary: "Balanced profile with practical SAP FI exposure and solid German communication readiness.",
    ai_skills: [
      { skill: "SAP FI", level: "Advanced" },
      { skill: "S/4HANA", level: "Intermediate" },
      { skill: "German communication", level: "B2" },
    ],
    missing_docs: [],
    next_steps: { text: "Invite to live case interview", link: "/admin/interviews" },
  },
  {
    id: "app-002",
    user_id: "user-002",
    created_at: daysAgo(6),
    status: "pending",
    pipeline_stage: "APPLIED",
    type: "course_application",
    course_name: "SAP MM Fast Track",
    name: "Omar Benali",
    email: "omar.benali@example.com",
    phone: "+212623456789",
    sap_track: "MM",
    german_level: "B1",
    experience_years: 2,
    admin_rating: 3,
    admin_notes: "Promising learner, needs stronger logistics process storytelling.",
    ai_analysis_summary: "Early-career candidate with high growth potential and solid fundamentals.",
    ai_skills: [
      { skill: "SAP MM", level: "Intermediate" },
      { skill: "Procure-to-Pay", level: "Intermediate" },
      { skill: "Excel", level: "Advanced" },
    ],
    missing_docs: ["passport"],
    next_steps: { text: "Submit passport copy then proceed", link: "/talent/profile" },
  },
  {
    id: "app-003",
    user_id: "user-003",
    created_at: daysAgo(9),
    status: "approved",
    pipeline_stage: "HIRED",
    type: "talent_pool_registration",
    name: "Salma Naciri",
    email: "salma.naciri@example.com",
    phone: "+212634567890",
    sap_track: "SD",
    german_level: "C1",
    experience_years: 7,
    admin_rating: 5,
    admin_notes: "Excellent commercial process depth and strong stakeholder communication.",
    ai_analysis_summary: "Senior profile with immediate placement readiness for client-facing SAP SD roles.",
    ai_skills: [
      { skill: "SAP SD", level: "Expert" },
      { skill: "Order-to-Cash", level: "Expert" },
      { skill: "Solution workshops", level: "Advanced" },
    ],
    missing_docs: [],
    next_steps: { text: "Move to shortlist and salary discussion", link: "/company/applicants" },
  },
  {
    id: "app-004",
    user_id: "user-004",
    created_at: daysAgo(13),
    status: "contacted",
    pipeline_stage: "INTERVIEW",
    type: "course_application",
    course_name: "SAP BTP Developer Path",
    name: "Mehdi Zahiri",
    email: "mehdi.zahiri@example.com",
    phone: "+212645678901",
    sap_track: "BTP",
    german_level: "A2",
    experience_years: 1,
    admin_rating: 3,
    admin_notes: "Technical curiosity is strong, language support required.",
    ai_analysis_summary: "Good technical fundamentals with clear motivation for SAP BTP growth.",
    ai_skills: [
      { skill: "JavaScript", level: "Intermediate" },
      { skill: "SAP BTP", level: "Beginner" },
      { skill: "REST APIs", level: "Intermediate" },
    ],
    missing_docs: ["certificates"],
    next_steps: { text: "Schedule technical assessment", link: "/admin/academy" },
  },
  {
    id: "app-005",
    user_id: "user-005",
    created_at: daysAgo(18),
    status: "rejected",
    pipeline_stage: "REJECTED",
    type: "talent_pool_registration",
    name: "Nora Boussaid",
    email: "nora.boussaid@example.com",
    phone: "+212656789012",
    sap_track: "ABAP",
    german_level: "B1",
    experience_years: 0,
    admin_rating: 2,
    admin_notes: "Needs foundational SAP training before pool entry.",
    ai_analysis_summary: "Early stage profile; recommend learning path before placement process.",
    ai_skills: [
      { skill: "ABAP", level: "Beginner" },
      { skill: "SQL", level: "Intermediate" },
      { skill: "OOP", level: "Intermediate" },
    ],
    missing_docs: ["cv", "passport"],
    next_steps: { text: "Enroll in fundamentals track", link: "/talent/learning" },
  },
  {
    id: "app-006",
    user_id: "user-006",
    created_at: daysAgo(26),
    status: "accepted",
    pipeline_stage: "OFFER",
    type: "talent_pool_registration",
    name: "Karim Lahlou",
    email: "karim.lahlou@example.com",
    phone: "+212667890123",
    sap_track: "FI",
    german_level: "B2",
    experience_years: 5,
    admin_rating: 4,
    admin_notes: "Good all-around profile with consulting background.",
    ai_analysis_summary: "Consistent performer with strong process understanding and interview readiness.",
    ai_skills: [
      { skill: "SAP FI", level: "Advanced" },
      { skill: "Controlling basics", level: "Intermediate" },
      { skill: "Client communication", level: "Advanced" },
    ],
    missing_docs: [],
    next_steps: { text: "Move to company interview pipeline", link: "/company/applicants" },
  },
];

export const mockActivityByApplicationId: Record<string, Array<{ action: string; created_at: string }>> = {
  "app-001": [
    { action: "profile_created", created_at: daysAgo(2) },
    { action: "documents_verified", created_at: daysAgo(1) },
    { action: "admin_review_completed", created_at: daysAgo(0) },
  ],
  "app-002": [
    { action: "application_submitted", created_at: daysAgo(6) },
    { action: "request_missing_document", created_at: daysAgo(5) },
  ],
  "app-003": [
    { action: "talent_pool_shortlisted", created_at: daysAgo(8) },
    { action: "status_approved", created_at: daysAgo(7) },
  ],
};
